name: deploy to aliyun oss

on:
  push:
    branches:
      - main # main 分支 push 事件触发任务
#  schedule:
#  - cron:  '10 00 * * 1,4' # 特定时间执行任务

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 切代码到 runner
    - run: |
        node -v
    - run: |
        free -h
    - run: ls -lah
    - uses: actions/checkout@v1
      with:
        submodules: true
    - run: ls -lah
    # 下载 git submodule
    #- uses: srt32/git-actions@v0.0.3
    #  with:
     #   args: git submodule update --init --recursive

    # 使用特定 node 版本打包
    # - name: use Node.js 14.x
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: 14.x
    # - run: |
    #     node -v
